/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mastodonMarketplaceSol from "./MastodonMarketplace.sol";
export type { mastodonMarketplaceSol };
export type { Lock } from "./Lock";
