/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDxnBuyAndBurn,
  IDxnBuyAndBurnInterface,
} from "../../../contracts/IDxnBuyBurn.sol/IDxnBuyAndBurn";

const _abi = [
  {
    inputs: [],
    name: "burnDXN",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDxnBuyAndBurn__factory {
  static readonly abi = _abi;
  static createInterface(): IDxnBuyAndBurnInterface {
    return new Interface(_abi) as IDxnBuyAndBurnInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDxnBuyAndBurn {
    return new Contract(address, _abi, runner) as unknown as IDxnBuyAndBurn;
  }
}
