/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MastodonMarketplace } from "./MastodonMarketplace";
export type { TipsyERC721Marketplace } from "./TipsyERC721Marketplace";
